name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get install libkrb5-dev
          python3 -m pip install --upgrade pip
          pip3 install -e .
      - name: Run tests
        run: pushd tests; python3 runner.py; popd
